version: '3'

services:
  nginx-proxy:
    restart: always
    container_name: nginx_proxy
    build:
      context: ./nginx-proxy
      dockerfile: ${DOCKER_FILE}
    ports:
      - '8080:8080'

  redis:
    image: 'redis:latest'

  api:
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_PORT=${SERVER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    build:
      context: ./server
      dockerfile: ${DOCKER_FILE}
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=${NODE_ENV}
      - CLIENT_PORT=${CLIENT_PORT}
    build:
      context: ./client
      dockerfile: ${DOCKER_FILE}
    volumes:
      - /app/node_modules
      - ./client:/app
