version: '3'

services:
  nginx-proxy:
    restart: always
    build:
      context: ./nginx-proxy
      dockerfile: ${DOCKER_FILE}
    ports:
      - '80:80'

  redis:
    image: 'redis:latest'

  api:
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    build:
      context: ./server
      dockerfile: ${DOCKER_FILE}
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: ${DOCKER_FILE}
    volumes:
      - /app/node_modules
      - ./client:/app
