FROM mhart/alpine-node

WORKDIR /code

RUN apk update && apk upgrade && apk add --no-cache bash

RUN addgroup -S node \
    && adduser -S -G node node \
    && chown -R node:node /code

USER node

COPY package.json .

RUN yarn install

COPY . .

CMD [ "yarn", "start:dev" ]